export enum ShapePropertyName {
  id = 'id',
  style = 'style',
  originX = 'originX',
  originY = 'originY',
  originalWidth = 'originalWidth',
  originalHeight = 'originalHeight',
  width = 'width',
  height = 'height',
  scaleX = 'scaleX',
  scaleY = 'scaleY',
  minWidth = 'minWidth',
  minHeight = 'minHeight',
  // invertable = 'invertable',
  horizontallyInvertable = 'horizontallyIvertable',
  verticallyInvertable = 'verticallyIvertable',
  horizontalInverted = 'horizontalInverted',
  verticallyInverted = 'verticallyInverted',
  edited = 'edited',
  selected = 'selected',
  shapes = 'shapes',
  src = 'src',
  text = 'text',
  wrap = 'wrap',
  points = 'points',
}
